general {
    lock_cmd = pidof hyprlock || hyprlock       # Запускает блокировщик, если он еще не запущен
    before_sleep_cmd = loginctl lock-session    # Блокировка перед уходом в сон
    after_sleep_cmd = hyprctl dispatch dpms on  # Включение экрана после пробуждения
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
