# --- Основные настройки ---
general {
    grace = 5
    ignore_empty_input = true
    immediate_render = true
}

auth {
    pam:enabled = true
    pam:module = hyprlock
    fingerprint:enabled = true
    fingerprint:ready_message = Scan fingerprint to unlock
    fingerprint:present_message = Scanning fingerprint...
}

# --- Фон ---
background {
    monitor = eDP-1
    path = /home/danya/wallpapers/daniel-leone-v7daTKlZzaw-unsplash.jpg
    blur_passes = 2
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# --- Поле ввода пароля ---
input-field {
    monitor = eDP-1
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(151515)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    fade_on_empty = false
    placeholder_text = <i>Input Password or Scan Finger...</i>
    hide_input = false
    position = 0, -40
    halign = center
    valign = center
}

# --- Часы ---
label {
    monitor = eDP-1
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(242, 243, 244, 0.75)
    font_size = 95
    font_family = JetBrains Mono Extrabold
    position = 0, 200
    halign = center
    valign = center
}

# --- Подсказка для отпечатка пальца ---
label {
    monitor = eDP-1
    text = 󰈟 Touch fingerprint sensor
    color = rgba(200, 200, 200, 0.6)
    font_size = 16
    font_family = JetBrains Mono
    position = 0, -110
    halign = center
    valign = center
}
